services:
  cliente:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./src:/bACKup/src:ro
      - ./makefile:/bACKup/makefile:ro
  servidor:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./src:/bACKup/src:ro
      - ./makefile:/bACKup/makefile:ro
networks:
  default:
    # Ler https://docs.docker.com/engine/network/drivers/macvlan/
    # para entender o porque precisa do driver de macvlan e do parent=eth0
    driver: macvlan
    driver_opts:
      com.docker.network.macvlan.parent: "eth0"
